export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik's cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "Iron Man racing a Formula 1 car on Mars, cinematic lighting", // new prompts from here
  "A futuristic cricket match on the moon with zero gravity, digital art",
  "A portrait of Elon Musk standing next to a Cybertruck on Mars, ultra-realistic",
  "MS Dhoni hitting a six in a neon-lit futuristic stadium, cyberpunk style",
  "A Formula 1 race between Batman's Batmobile and a Ferrari, hyper-realistic",
  "A photo-realistic image of Cristiano Ronaldo scoring a goal in a stadium filled with AI robots",
  "A Marvel-style illustration of Virat Kohli as a superhero wielding a cosmic bat",
  "A breathtaking view of Earth rising over the Moon, captured from a space station",
  "A magical rangoli pattern inspired by Van Gogh's Starry Night, digital art",
  "An astronaut riding a space whale through the Milky Way galaxy, mesmerizing visuals",
  "A sports bike drifting on a highway with flames coming from its wheels, hyper-realistic",
  "A Bollywood-style poster featuring Shah Rukh Khan as a time-traveling warrior",
  "A robotic farmer harvesting golden wheat fields under a stunning sunset, ultra-detailed",
  "A Tesla Cybertruck transformed into a spaceship exploring the Andromeda galaxy",
  "Sachin Tendulkar playing cricket with aliens on an exoplanet, stunning visuals",
  "A Lamborghini Aventador floating on a neon-lit cyber highway in the year 2077",
  "A traditional Indian farmer using an AI-powered plow in a futuristic village, hyper-realistic",
  "A 3D-rendered superhero version of Sundar Pichai coding in a secret Google lab",
  "A drone-assisted football match in the year 2050 with AI referees, hyper-detailed",
  "An aerial view of an F1 car racing on a track that floats in the clouds",
  "A hyper-realistic football match between Messi and Ronaldo on an asteroid",
  "Mahatma Gandhi in a modern-day political debate, digital realism",
  "The Taj Mahal at sunset, but with cyberpunk neon lights illuminating its domes",
  "A spaceship designed by Tony Stark exploring the farthest reaches of the universe",
  "A sports bike speeding through a cyberpunk Tokyo street with neon reflections",
  "A Formula 1 race happening on Saturn's rings, ultra-detailed digital art",
  "A historical painting of Steve Jobs launching the first iPhone, ultra-realistic",
  "A Ferrari LaFerrari parked on a scenic Mars landscape under a starry sky",
  "A photo-realistic image of Leonardo da Vinci using an iPad to design the Mona Lisa",
  "A Marvel vs. DC battle happening in a futuristic New York City skyline",
  "The Great Wall of China covered in breathtaking snow during winter, drone shot",
  "A scenic view of the entire solar system with all planets in perfect alignment",
  "A cricket stadium on top of Mount Everest, capturing an intense final match",
  "A surreal dream-like painting of a tiger running through waves on a beach",
  "The Avengers assembled inside the ISS (International Space Station), hyper-realistic",
  "A traditional Indian festival celebration in space with floating diyas and colors",
  "An F1 race track built entirely on the ocean with futuristic cars zooming by",
  "A grand rangoli design shaped like the Milky Way galaxy, ultra-detailed",
  "Sachin Tendulkar and Virat Kohli playing cricket on a holographic stadium",
  "A sports car racing on an invisible track that only appears when it moves",
  "A giant wave forming the shape of Lionel Messi kicking a football, surreal art",
  "A Formula 1 car transforming into a spaceship mid-race and launching into space",
  "A cyberpunk rendition of Albert Einstein working on a futuristic quantum computer",
  "A time-traveling Cristiano Ronaldo playing football in the 1800s with Victorian-era clothes",
  "A luxurious Bugatti Chiron floating above a city skyline, digital art",
  "A portrait of Ratan Tata in a futuristic Tata Motors factory, ultra-detailed",
  "A hyper-realistic scene of Earth as viewed from the rings of Saturn",
  "An astronaut playing cricket on an asteroid, slow-motion capture",
  "A farmer using a robotic exoskeleton to plow fields, ultra-detailed",
  "A surreal image of the Eiffel Tower submerged in crystal-clear ocean water",
  "Captain america fighting with hulk in snow mountains, realistic art",
];
