export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  "a sea otter with a pearl earring by Johannes Vermeer",
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik's cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "Iron Man racing a Formula 1 car on Mars, cinematic lighting", // from here: new simple prompts
  "a giraffe reading a book under a tree, watercolor style",
  "a robot watering plants in a small garden, digital art",
  "a cartoon fox riding a skateboard through the city",
  "a penguin wearing a tuxedo at a fancy dinner party",
  "a lighthouse on a floating island during sunset",
  "a space cat exploring a colorful alien planet, digital art",
  "a snail with a tiny city on its shell, hand-drawn illustration",
  "a wizard owl casting a spell in a magical forest",
  "a futuristic coffee shop on the moon with astronauts as customers",
  "a group of animals having a picnic in a sunny meadow",
  "a donut flying through space with a trail of sprinkles",
  "a neon-colored jellyfish swimming through a dark ocean",
  "a cat astronaut floating inside a cozy space station",
  "a retro arcade machine in the middle of a desert",
  "a ghost drinking tea on a rainy day, cozy illustration",
  "a flying turtle with rocket boosters, cartoon style",
  "a steampunk-inspired city powered by wind turbines",
  "a cozy cabin in the mountains under a starry sky, digital painting",
  "a rabbit detective solving a mystery in a noir setting",
  "a frog sitting on a lily pad playing the guitar"
];
